# Generated by Django 6.0.2 on 2026-02-12 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Panc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_comum', models.CharField(max_length=100, verbose_name='Nome Comum')),
                ('nome_cientifico', models.CharField(max_length=100, verbose_name='Nome Científico')),
                ('descricao_curta', models.CharField(help_text='Texto que aparece no card', max_length=200)),
                ('foto_capa', models.ImageField(upload_to='pancs/capas/', verbose_name='Foto do Card')),
                ('descricao_completa', models.TextField(blank=True, verbose_name='Descrição Completa')),
                ('familia_botanica', models.CharField(blank=True, max_length=100)),
                ('uso_medicinal', models.CharField(blank=True, max_length=200)),
                ('proteina', models.CharField(blank=True, help_text='Ex: 25%', max_length=50)),
                ('video_youtube', models.URLField(blank=True, help_text='Link do vídeo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogo.categoria')),
            ],
            options={
                'verbose_name': 'PANC',
                'verbose_name_plural': 'PANCs',
            },
        ),
    ]
